### ISSUE TITLE
Template feedback

### ISSUE THREAD

**Issue by brody192** [mkizka/misskey-railway-template#1]
Wonderfull template! I only have one small suggestion.
On the `Misskey` service, you have a `MISSKEY__URL` variable but opted not to set `https://${{RAILWAY_PUBLIC_DOMAIN}}` as its default value.
Maybe you thought that variable would only render out to the Railway-provided domain?

If a custom domain is set on the service, that variable will render out to the custom domain, otherwise, it will render out to the railway domain.

So in my opinion you should set that value as the default value.

oh and if you feel like it? give the template an applicable logo.

**Comment by mkizka** [comment]
@brody192 Thank you for your feedback.

I understand that the custom domain is rendered. However, in Misskey, it is necessary to decide the URL at the start of the service, and once set, the URL cannot be changed. I thought that if I set a default value in the template, it would become "pre-configured" and people might forget to set it. I did not set a default value in order to say to users that the setting is essentially mandatory.

![image](https://github.com/mkizka/misskey-railway-template/assets/30231179/3f6423af-4222-40ab-a7cf-b4b1fb221e35)

Additionally, I had once set an icon, but I deleted it because the license of Misskey's icon was not clear. I am currently checking with the maintainer of Misskey.

**Comment by brody192** [comment]
oh, that variable is a single set variable? misskey doesn't allow you to change it after the fact? have you tried this?
I have seen single set variables, but they have all been database username/password variables

**Comment by mkizka** [comment]
@brody192 You can change it before starting the instance, but changing it after starting will break federation (a feature of ActivityPub). This is written in Misskey like this:

> ONCE YOU HAVE STARTED THE INSTANCE, DO NOT CHANGE THE URL SETTINGS AFTER THAT!
> https://github.com/misskey-dev/misskey/blob/14aedc17ae4e3ca3db9e523f2663824e874e0569/.config/example.yml#L11-L12

Users must always configure it before deploying from the template.

**Comment by brody192** [comment]
that's an incredibly bad and limiting design decision on their part imo, I'm genuinely surprised. but nothing you can do about that so your decision to not set the variable reference as the default was a good call, thank you for showing me that and thank you for the template!!
